class CreditCardAffiliateConfig {
  CreditCardAffiliateConfig._();

  // ============================================================
  // CREDIT CARD AFFILIATE URLS
  //
  // Cuelinks URLs will be pasted here after approval.
  //
  // DO NOT put normal bank URLs here.
  // Use the tracking URLs generated by Cuelinks.
  // ============================================================

  static const String sbiUrl = '';

  static const String hdfcUrl = '';

  static const String axisUrl = '';

  static const String iciciUrl = '';

  // ============================================================
  // Internal IDs
  // ============================================================

  static const String sbiId = 'sbi';

  static const String hdfcId = 'hdfc';

  static const String axisId = 'axis';

  static const String iciciId = 'icici';

  // ============================================================
  // Internal source/sub IDs
  // ============================================================

  static const String sbiSubId = 'FCH_SBI';

  static const String hdfcSubId = 'FCH_HDFC';

  static const String axisSubId = 'FCH_AXIS';

  static const String iciciSubId = 'FCH_ICICI';
}
